### ISSUE TITLE
Void idol ascended and radiant settings don't work

### ISSUE THREAD

**Issue by midowido** [BadMagic100/TheRealJournalRando#24]
When putting the void idol setting on ascended or radiant the randomizer doesn't work. It just keeps randomizing forever unable to get a successful attempt.

**Comment by BadMagic100** [comment]
Most often this kind of error is due to incompatibility with another connection mod. Please provide a modlog in order to diagnose the issue as well as list other enabled connections.

**Comment by midowido** [comment]
The only mods I have on apart from this one is the randomizer 4 mod and its dependencies: Benchwarp, Itemchanger, Menuchanger, Qol, Randomizercore, Randomizercore.json, and Vasi.

**Comment by midowido** [comment]
I also did a test where I only randomized the void idol on ascended and randomized nothing else and it still didn't work.

**Comment by BadMagic100** [comment]
Please still provide a modlog to expedite troubleshooting

**Comment by midowido** [comment]
I'm sorry could you explain where I can find that and what files I need exactly?

**Comment by BadMagic100** [comment]
Modlog.txt from one of these locations, or a timestamped modlog from the Old Modlogs folder within these locations. Looking for a log from a session where generation froze/failed. Would likely have many errors listed in it
 
Windows: 
Save Files: %APPDATA%\..\LocalLow\Team Cherry\Hollow Knight\
 
Mac OS: 
Save Files: ~/Library/Application Support/unity.Team Cherry.Hollow Knight/ 

Linux: 
Save Files: ~/.config/unity3d/Team Cherry/Hollow Knight/

**Comment by midowido** [comment]
[ModLog.txt](https://github.com/user-attachments/files/16103330/ModLog.txt)

**Comment by midowido** [comment]
[ModLog.txt](https://github.com/user-attachments/files/16103338/ModLog.txt)
The first one was with the setting on ascended and this one is with the setting on radiant.

**Comment by BadMagic100** [comment]
Is attuned broken as well or just ascended and radiant?

**Comment by BadMagic100** [comment]
Confirmed this is due to a slightly unexpected behavior in the randomizer library, currently in discussion to determine where the fix will be done

**Comment by midowido** [comment]
Good to hear you found the issue.
And no attuned is not broken just ascended and radiant.

**Comment by BadMagic100** [comment]
This should be corrected by 0ff14920e6af228eaef4825d7a9b70283c00c4be

Updating the mod shortly

**Comment by BadMagic100** [comment]
The update has been released that should fix the issue
